"""Small, dependency-free security and operational runtime helpers.

The helpers in this module are deliberately Flask-agnostic.  ``app.py`` can
wire them into request hooks without making the security policy, rate-limit
state, or metrics storage part of the already large application module.
"""

from __future__ import annotations

import hashlib
import ipaddress
import json
import math
import os
import re
import sqlite3
import threading
import time
from contextlib import closing
from dataclasses import dataclass
from typing import Iterable, Mapping


COMPAT_CONTENT_SECURITY_POLICY = "; ".join((
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self'",
    "manifest-src 'self'",
    "worker-src 'self'",
))


@dataclass(frozen=True)
class SecurityHeadersConfig:
    """Response-header policy compatible with LibFlix's current templates.

    The current UI contains inline script blocks, style blocks/attributes, and
    event attributes generated by trusted templates.  Compatibility mode
    therefore permits inline script and style execution, but closes every
    network capability to same-origin and blocks framing, plugins, base-tag
    changes, and cross-origin form submission.  Once inline handlers have been
    removed, callers can provide a stricter CSP without changing this helper.
    """

    content_security_policy: str = COMPAT_CONTENT_SECURITY_POLICY
    trust_forwarded_proto: bool = False
    hsts_max_age: int = 31_536_000
    hsts_include_subdomains: bool = False


def _forwarded_https(headers: Mapping[str, str]) -> bool:
    forwarded = headers.get("Forwarded", "")
    for item in forwarded.split(","):
        match = re.search(r"(?:^|;)\s*proto=\"?([^;\",\s]+)", item, re.I)
        if match:
            return match.group(1).casefold() == "https"
    forwarded_proto = headers.get("X-Forwarded-Proto", "").split(",", 1)[0]
    return forwarded_proto.strip().casefold() == "https"


def request_is_https(request, *, trust_forwarded_proto: bool = False) -> bool:
    """Return true only for direct TLS or an explicitly trusted TLS proxy."""

    if bool(getattr(request, "is_secure", False)):
        return True
    if not trust_forwarded_proto:
        return False
    return _forwarded_https(getattr(request, "headers", {}))


def apply_security_headers(response, request, config: SecurityHeadersConfig | None = None):
    """Apply browser security headers without changing cache or content headers."""

    config = config or SecurityHeadersConfig()
    headers = response.headers
    headers.setdefault("Content-Security-Policy", config.content_security_policy)
    headers.setdefault("X-Content-Type-Options", "nosniff")
    headers.setdefault("X-Frame-Options", "DENY")
    headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    headers.setdefault(
        "Permissions-Policy",
        "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
    )
    headers.setdefault("Cross-Origin-Opener-Policy", "same-origin")
    if request_is_https(request, trust_forwarded_proto=config.trust_forwarded_proto):
        hsts = f"max-age={max(0, int(config.hsts_max_age))}"
        if config.hsts_include_subdomains:
            hsts += "; includeSubDomains"
        headers.setdefault("Strict-Transport-Security", hsts)
    return response


@dataclass(frozen=True)
class RateLimitRule:
    """Token-bucket capacity replenished evenly over ``period_seconds``."""

    capacity: int
    period_seconds: float

    def __post_init__(self):
        if self.capacity <= 0 or self.period_seconds <= 0:
            raise ValueError("Rate limits require positive capacity and period")


@dataclass(frozen=True)
class RateLimitDecision:
    allowed: bool
    limit: int
    remaining: int
    retry_after: int = 0
    degraded: bool = False

    @property
    def response_headers(self) -> dict[str, str]:
        headers = {
            "X-RateLimit-Limit": str(self.limit),
            "X-RateLimit-Remaining": str(max(0, self.remaining)),
        }
        if not self.allowed:
            headers["Retry-After"] = str(max(1, self.retry_after))
        return headers


def request_client_identity(
    request,
    *,
    trusted_client_ip_header: str = "",
    trusted_proxy_networks: Iterable[str] = (),
) -> str:
    """Resolve a client IP without treating public request headers as proof.

    A rewritten client-IP header is considered only when the immediate peer is
    inside an explicitly trusted network.  This supports a localhost reverse
    proxy while ignoring forged Cloudflare and forwarding headers by default.
    """

    try:
        peer = ipaddress.ip_address(str(getattr(request, "remote_addr", "") or "").strip())
    except ValueError:
        peer = None
    trusted_peer = False
    if peer:
        for network in trusted_proxy_networks:
            try:
                trusted_peer = peer in ipaddress.ip_network(network, strict=False)
            except ValueError:
                continue
            if trusted_peer:
                break
    if trusted_client_ip_header and trusted_peer:
        candidate = str(
            getattr(request, "headers", {}).get(trusted_client_ip_header, "")
        ).strip()
        try:
            return ipaddress.ip_address(candidate).compressed
        except ValueError:
            pass
    return peer.compressed if peer else "unknown"


class SQLiteRateLimiter:
    """Cross-process token buckets backed by SQLite.

    Database failures fail open: a locked or unavailable limiter must not turn
    into a public-site outage.  Identities are stored as hashes, old buckets are
    expired, and the table is hard-capped to keep hostile cardinality bounded.
    """

    def __init__(
        self,
        database_path: str,
        *,
        retention_seconds: int = 86_400,
        max_entries: int = 20_000,
        timeout: float = 0.25,
    ):
        self.database_path = os.path.abspath(database_path)
        self.retention_seconds = max(60, int(retention_seconds))
        self.max_entries = max(100, int(max_entries))
        self.timeout = max(0.01, float(timeout))
        self._schema_lock = threading.Lock()
        self._schema_ready = False
        self._state_lock = threading.Lock()
        self._next_prune_at = 0.0
        self._new_entries_since_prune = 0
        self._prune_batch = max(10, min(64, self.max_entries // 10))
        self.degraded_checks = 0

    def _connect(self) -> sqlite3.Connection:
        directory = os.path.dirname(self.database_path)
        os.makedirs(directory, mode=0o700, exist_ok=True)
        connection = sqlite3.connect(
            self.database_path,
            timeout=self.timeout,
            isolation_level=None,
        )
        connection.execute(f"PRAGMA busy_timeout={int(self.timeout * 1000)}")
        return connection

    def _ensure_schema(self, connection: sqlite3.Connection) -> None:
        if self._schema_ready:
            return
        with self._schema_lock:
            if self._schema_ready:
                return
            connection.execute("PRAGMA journal_mode=WAL")
            connection.execute("PRAGMA synchronous=NORMAL")
            connection.execute(
                "CREATE TABLE IF NOT EXISTS rate_limit_buckets ("
                "bucket TEXT NOT NULL, identity_hash TEXT NOT NULL, "
                "tokens REAL NOT NULL, updated_at REAL NOT NULL, "
                "PRIMARY KEY(bucket, identity_hash))"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS rate_limit_updated_at "
                "ON rate_limit_buckets(updated_at)"
            )
            try:
                os.chmod(self.database_path, 0o600)
            except OSError:
                pass
            self._schema_ready = True

    @staticmethod
    def _identity_hash(bucket: str, identity: str) -> str:
        material = f"libflix-rate-limit\0{bucket}\0{identity}".encode("utf-8")
        return hashlib.sha256(material).hexdigest()

    def check(
        self,
        bucket: str,
        identity: str,
        rule: RateLimitRule,
        *,
        cost: float = 1.0,
        now: float | None = None,
    ) -> RateLimitDecision:
        if not re.fullmatch(r"[a-z0-9_.:-]{1,80}", bucket):
            raise ValueError("Invalid rate-limit bucket")
        if not math.isfinite(cost) or cost <= 0 or cost > rule.capacity:
            raise ValueError("Invalid rate-limit cost")
        now = time.time() if now is None else float(now)
        identity_hash = self._identity_hash(bucket, str(identity)[:256])
        try:
            with closing(self._connect()) as connection:
                self._ensure_schema(connection)
                connection.execute("BEGIN IMMEDIATE")
                row = connection.execute(
                    "SELECT tokens, updated_at FROM rate_limit_buckets "
                    "WHERE bucket = ? AND identity_hash = ?",
                    (bucket, identity_hash),
                ).fetchone()
                is_new = row is None
                if row is None:
                    tokens = float(rule.capacity)
                else:
                    elapsed = max(0.0, now - float(row[1]))
                    refill_rate = rule.capacity / rule.period_seconds
                    tokens = min(float(rule.capacity), float(row[0]) + elapsed * refill_rate)

                allowed = tokens >= cost
                if allowed:
                    tokens -= cost
                connection.execute(
                    "INSERT INTO rate_limit_buckets(bucket, identity_hash, tokens, updated_at) "
                    "VALUES (?, ?, ?, ?) ON CONFLICT(bucket, identity_hash) DO UPDATE SET "
                    "tokens = excluded.tokens, updated_at = excluded.updated_at",
                    (bucket, identity_hash, tokens, now),
                )
                with self._state_lock:
                    if is_new:
                        self._new_entries_since_prune += 1
                    prune_due = bool(is_new and (
                        now >= self._next_prune_at
                        or self._new_entries_since_prune >= self._prune_batch
                    ))
                if prune_due:
                    connection.execute(
                        "DELETE FROM rate_limit_buckets WHERE updated_at < ?",
                        (now - self.retention_seconds,),
                    )
                    count = connection.execute(
                        "SELECT COUNT(*) FROM rate_limit_buckets"
                    ).fetchone()[0]
                    overflow = max(0, count - self.max_entries)
                    if overflow:
                        connection.execute(
                            "DELETE FROM rate_limit_buckets WHERE rowid IN ("
                            "SELECT rowid FROM rate_limit_buckets "
                            "ORDER BY updated_at ASC LIMIT ?)",
                            (overflow,),
                        )
                connection.commit()
                if prune_due:
                    with self._state_lock:
                        self._next_prune_at = max(self._next_prune_at, now + 3_600)
                        self._new_entries_since_prune = 0

            if allowed:
                retry_after = 0
            else:
                refill_rate = rule.capacity / rule.period_seconds
                retry_after = max(1, math.ceil((cost - tokens) / refill_rate))
            return RateLimitDecision(
                allowed=allowed,
                limit=rule.capacity,
                remaining=max(0, math.floor(tokens)),
                retry_after=retry_after,
            )
        except (OSError, sqlite3.Error):
            with self._state_lock:
                self.degraded_checks += 1
            return RateLimitDecision(
                allowed=True,
                limit=rule.capacity,
                remaining=rule.capacity,
                degraded=True,
            )

    def healthcheck(self) -> bool:
        """Verify the enforcement database can take a write lock."""

        try:
            with closing(self._connect()) as connection:
                self._ensure_schema(connection)
                connection.execute("BEGIN IMMEDIATE")
                connection.execute("SELECT COUNT(*) FROM rate_limit_buckets").fetchone()
                connection.rollback()
            return True
        except (OSError, sqlite3.Error):
            return False


_KNOWN_METRICS = frozenset({
    "web.navigation_ms",
    "web.fcp_ms",
    "web.lcp_ms",
    "web.inp_ms",
    "web.cls",
    "http.requests",
    "http.duration_ms",
    "http.errors",
    "server.exceptions",
})


def normalize_metric_route(path_or_rule: str | None) -> str:
    """Collapse user-controlled IDs/topics so metric series stay bounded."""

    value = str(path_or_rule or "").split("?", 1)[0][:300]
    patterns = (
        (r"^/(?:fiction/)?(?:cn/)?book/[^/]+/?$", "/book/<work_id>"),
        (r"^/(?:fiction/)?(?:cn/)?category/[^/]+/?$", "/category/<topic>"),
        (r"^/api/category/[^/]+/?$", "/api/category/<topic>"),
        (r"^/api/shelf/[^/]+/?$", "/api/shelf/<topic>"),
        (r"^/api/kindle/jobs/[^/]+/?$", "/api/kindle/jobs/<job_id>"),
        (r"^/(?:download|cover|olcover|iacover)/[^/]+(?:/[^/]+)?/?$", "/asset/<id>"),
    )
    for pattern, route in patterns:
        if re.fullmatch(pattern, value):
            return route
    fixed = {
        "/", "/fiction", "/cn", "/fiction/cn", "/topics", "/cn/topics", "/discover",
        "/fiction/discover", "/cn/discover", "/fiction/cn/discover",
        "/search", "/preview", "/api/search", "/api/discover",
        "/api/book", "/api/similar", "/api/kindle/jobs",
        "/api/sendtokindle", "/api/metrics/web-vitals", "/api/health",
    }
    return value.rstrip("/") or "/" if value in fixed or value.rstrip("/") in fixed else "/other"


@dataclass(frozen=True)
class MetricEvent:
    name: str
    value: float
    route: str = "/other"
    label: str = ""


class SQLiteMetrics:
    """Hourly aggregates with no raw paths, payloads, IPs, or error messages."""

    def __init__(
        self,
        database_path: str,
        *,
        retention_seconds: int = 30 * 86_400,
        max_rows: int = 50_000,
        timeout: float = 0.25,
    ):
        self.database_path = os.path.abspath(database_path)
        self.retention_seconds = max(3_600, int(retention_seconds))
        self.max_rows = max(100, int(max_rows))
        self.timeout = max(0.01, float(timeout))
        self._schema_lock = threading.Lock()
        self._schema_ready = False
        self._state_lock = threading.Lock()
        self._next_prune_at = 0.0
        self.dropped_writes = 0

    def _connect(self) -> sqlite3.Connection:
        os.makedirs(os.path.dirname(self.database_path), mode=0o700, exist_ok=True)
        connection = sqlite3.connect(self.database_path, timeout=self.timeout)
        connection.execute(f"PRAGMA busy_timeout={int(self.timeout * 1000)}")
        return connection

    def _ensure_schema(self, connection: sqlite3.Connection) -> None:
        if self._schema_ready:
            return
        with self._schema_lock:
            if self._schema_ready:
                return
            connection.execute("PRAGMA journal_mode=WAL")
            connection.execute("PRAGMA synchronous=NORMAL")
            connection.execute(
                "CREATE TABLE IF NOT EXISTS metric_hourly ("
                "bucket_start INTEGER NOT NULL, metric TEXT NOT NULL, "
                "route TEXT NOT NULL, label TEXT NOT NULL, count INTEGER NOT NULL, "
                "total REAL NOT NULL, minimum REAL NOT NULL, maximum REAL NOT NULL, "
                "PRIMARY KEY(bucket_start, metric, route, label))"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS metric_hourly_bucket "
                "ON metric_hourly(bucket_start)"
            )
            connection.commit()
            try:
                os.chmod(self.database_path, 0o600)
            except OSError:
                pass
            self._schema_ready = True

    @staticmethod
    def _clean_label(label: str) -> str:
        label = str(label or "")[:80]
        return label if re.fullmatch(r"[A-Za-z0-9_.:/-]{0,80}", label) else "other"

    def record(self, events: Iterable[MetricEvent], *, now: float | None = None) -> bool:
        now = time.time() if now is None else float(now)
        bucket_start = int(now // 3_600 * 3_600)
        cleaned: list[tuple[str, float, str, str]] = []
        for event in events:
            if event.name not in _KNOWN_METRICS:
                continue
            value = float(event.value)
            if not math.isfinite(value) or value < 0 or value > 1_000_000_000:
                continue
            cleaned.append((
                event.name,
                value,
                normalize_metric_route(event.route),
                self._clean_label(event.label),
            ))
        if not cleaned:
            return False
        try:
            with closing(self._connect()) as connection:
                self._ensure_schema(connection)
                for name, value, route, label in cleaned:
                    connection.execute(
                        "INSERT INTO metric_hourly("
                        "bucket_start, metric, route, label, count, total, minimum, maximum"
                        ") VALUES (?, ?, ?, ?, 1, ?, ?, ?) "
                        "ON CONFLICT(bucket_start, metric, route, label) DO UPDATE SET "
                        "count = count + 1, total = total + excluded.total, "
                        "minimum = MIN(minimum, excluded.minimum), "
                        "maximum = MAX(maximum, excluded.maximum)",
                        (bucket_start, name, route, label, value, value, value),
                    )
                with self._state_lock:
                    prune_due = now >= self._next_prune_at
                if prune_due:
                    connection.execute(
                        "DELETE FROM metric_hourly WHERE bucket_start < ?",
                        (int(now - self.retention_seconds),),
                    )
                    count = connection.execute("SELECT COUNT(*) FROM metric_hourly").fetchone()[0]
                    overflow = max(0, count - self.max_rows)
                    if overflow:
                        connection.execute(
                            "DELETE FROM metric_hourly WHERE rowid IN ("
                            "SELECT rowid FROM metric_hourly "
                            "ORDER BY bucket_start ASC LIMIT ?)",
                            (overflow,),
                        )
                connection.commit()
                if prune_due:
                    with self._state_lock:
                        self._next_prune_at = max(self._next_prune_at, now + 3_600)
            return True
        except (OSError, sqlite3.Error):
            with self._state_lock:
                self.dropped_writes += 1
            return False

    def record_web_vitals(self, payload: Mapping, *, now: float | None = None) -> bool:
        route = normalize_metric_route(payload.get("path"))
        names = {
            "navigation": "web.navigation_ms",
            "fcp": "web.fcp_ms",
            "lcp": "web.lcp_ms",
            "inp": "web.inp_ms",
            "cls": "web.cls",
        }
        events = []
        for source, destination in names.items():
            value = payload.get(source)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                upper = 100 if source == "cls" else 600_000
                if 0 <= value <= upper:
                    events.append(MetricEvent(destination, float(value), route))
        return self.record(events, now=now)

    def healthcheck(self) -> bool:
        """Verify the aggregate store can take a write lock."""

        try:
            with closing(self._connect()) as connection:
                self._ensure_schema(connection)
                connection.execute("BEGIN IMMEDIATE")
                connection.execute("SELECT COUNT(*) FROM metric_hourly").fetchone()
                connection.rollback()
            return True
        except (OSError, sqlite3.Error):
            return False

    def record_request(
        self,
        route: str,
        method: str,
        status: int,
        duration_ms: float,
        *,
        now: float | None = None,
    ) -> bool:
        method = method.upper() if method.upper() in {
            "GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"
        } else "OTHER"
        status_family = f"{max(0, min(9, int(status) // 100))}xx"
        label = f"{method}:{status_family}"
        events = [
            MetricEvent("http.requests", 1, route, label),
            MetricEvent("http.duration_ms", max(0.0, duration_ms), route, label),
        ]
        if int(status) >= 500:
            events.append(MetricEvent("http.errors", 1, route, status_family))
        return self.record(events, now=now)

    def record_exception(self, route: str, error: BaseException, *, now: float | None = None) -> bool:
        error_type = type(error).__name__
        label = error_type if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,79}", error_type) else "Exception"
        return self.record(
            [MetricEvent("server.exceptions", 1, route, label)],
            now=now,
        )

    def summary(self, *, since: float | None = None) -> list[dict]:
        since = time.time() - self.retention_seconds if since is None else float(since)
        try:
            with closing(self._connect()) as connection:
                self._ensure_schema(connection)
                rows = connection.execute(
                    "SELECT metric, route, label, SUM(count), SUM(total), "
                    "MIN(minimum), MAX(maximum) FROM metric_hourly "
                    "WHERE bucket_start >= ? GROUP BY metric, route, label "
                    "ORDER BY metric, route, label",
                    (int(since // 3_600 * 3_600),),
                ).fetchall()
        except (OSError, sqlite3.Error):
            return []
        return [
            {
                "metric": metric,
                "route": route,
                "label": label,
                "count": count,
                "average": total / count if count else 0,
                "minimum": minimum,
                "maximum": maximum,
            }
            for metric, route, label, count, total, minimum, maximum in rows
        ]


def json_rate_limit_body(retry_after: int) -> str:
    """Stable public response body for a 429 integration hook."""

    return json.dumps({
        "success": False,
        "error": "Too many requests. Please try again shortly.",
        "retry_after": max(1, int(retry_after)),
    }, separators=(",", ":"))
